name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build -t my-flask-app .
          docker tag my-flask-app my-flask-app:latest
          docker save my-flask-app:latest -o my-flask-app.tar
          
      - name: Upload Docker Image as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-flask-app  
          path: my-flask-app.tar 

  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: my-flask-app

      - name: Load and Run Tests
        run: |
          docker load -i my-flask-app.tar
          docker run --rm my-flask-app python -m unittest discover

  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > /tmp/kubeconfig
        env:
          KUBECONFIG: /tmp/kubeconfig
          
      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: /tmp/kubeconfig  
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > /tmp/kubeconfig
          docker load -i my-flask-app.tar
          kubectl apply -f /home/m/deployment.yaml
          kubectl expose deployment my-flask-app --type=NodePort --port=5000 --target-port=5000
          kubectl rollout status deployment/my-flask-app
